/**
 * Gallery photo data — AUTO-GENERATED by scripts/generate-gallery.mjs
 * Do not edit by hand. Run the script again after adding/removing images.
 * Edit individual fields (title, location, etc.) directly in this file.
 */

export interface Photo {
  src: string
  title: string
  date: string
  camera?: string
  lens?: string
  aperture?: string
  shutter?: string
  iso?: string
  focal?: string
  location?: string
}

const photos: Photo[] = [
  {
    src: '/gallery/1.jpg',
    title: '1',
    date: '2026-03-03',
    lens: '24-120mm',
    aperture: 'f/7.1',
    shutter: '1/1000s',
    iso: 'ISO 400',
    focal: '87mm',
  },
]

export default photos
