#!/usr/bin/env node

/**
 * generate-gallery.mjs
 *
 * Scans docs/.vuepress/public/gallery/ for images,
 * reads EXIF metadata via exifr, and writes gallery-data.ts.
 *
 * Usage:  node scripts/generate-gallery.mjs
 */

import { readdir, writeFile, stat } from 'node:fs/promises'
import { join, extname, basename, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const exifr = require('exifr')

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const ROOT = join(__dirname, '..')

const GALLERY_DIR = join(ROOT, 'docs', '.vuepress', 'public', 'gallery')
const DATA_FILE = join(ROOT, 'docs', '.vuepress', 'gallery-data.ts')

const IMG_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.tiff', '.tif', '.heic', '.heif'])

/**
 * Convert EXIF date string like "2026:06:15 14:30:00" → "2026-06-15"
 */
function normalizeDate(raw) {
  if (!raw) return null
  // ISO or YYYY-MM-DD
  const iso = /^(\d{4})-(\d{2})-(\d{2})/.exec(raw)
  if (iso) return `${iso[1]}-${iso[2]}-${iso[3]}`

  // EXIF format YYYY:MM:DD HH:mm:ss
  const exif = /^(\d{4}):(\d{2}):(\d{2})/.exec(raw)
  if (exif) return `${exif[1]}-${exif[2]}-${exif[3]}`

  return raw.slice(0, 10)
}

function cleanTitle(filename) {
  let name = basename(filename, extname(filename))
  // Replace underscores / hyphens / IMG_ prefixes
  name = name.replace(/^(IMG_|DSC_|DSCF|P|_DSC|DSC|IMG|image|photo)[-_]\s*/i, '')
  name = name.replace(/[-_]/g, ' ')
  name = name.trim()
  return name || basename(filename)
}

function formatShutter(s) {
  if (!s) return null
  if (typeof s === 'number') {
    if (s < 1) return `1/${Math.round(1 / s)}s`
    return `${s}s`
  }
  return String(s)
}

async function scanImages(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = []

  for (const e of entries) {
    if (e.isDirectory()) continue
    const ext = extname(e.name).toLowerCase()
    if (!IMG_EXT.has(ext)) continue

    const full = join(dir, e.name)
    const fileStat = await stat(full)

    let exif = {}
    try {
      exif = (await exifr.parse(full, {
        pick: [
          'Make', 'Model', 'LensModel', 'LensInfo',
          'FNumber', 'ExposureTime', 'ISO',
          'FocalLength', 'FocalLengthIn35mmFormat',
          'DateTimeOriginal', 'CreateDate', 'ModifyDate',
          'OffsetTimeOriginal', 'OffsetTimeDigitized',
          'GPSLatitude', 'GPSLongitude',
        ],
      })) || {}
    } catch {
      // EXIF read failed — use file stats
    }

    files.push({
      src: `/gallery/${e.name}`,
      // Prefer original filename as title base
      rawName: cleanTitle(e.name),
      date: normalizeDate(
        exif.DateTimeOriginal || exif.CreateDate || exif.ModifyDate
      ) || fileStat.mtime.toISOString().slice(0, 10),
      camera: exif.Make
        ? [exif.Make, exif.Model].filter(Boolean).join(' ')
        : null,
      lens: exif.LensModel
        || (Array.isArray(exif.LensInfo) && exif.LensInfo.length >= 2
          ? `${Math.round(exif.LensInfo[0])}-${Math.round(exif.LensInfo[1])}mm`
          : null)
        || null,
      aperture: exif.FNumber ? `f/${exif.FNumber}` : null,
      shutter: formatShutter(exif.ExposureTime),
      iso: exif.ISO ? `ISO ${exif.ISO}` : null,
      focal: exif.FocalLength
        ? `${Math.round(Number(exif.FocalLength))}mm`
        : null,
      location: null, // GPS → address not handled here; set manually
    })
  }

  // Sort by date descending
  files.sort((a, b) => b.date.localeCompare(a.date))
  return files
}

function generateDataFile(photos) {
  const lines = []
  lines.push('/**')
  lines.push(' * Gallery photo data — AUTO-GENERATED by scripts/generate-gallery.mjs')
  lines.push(' * Do not edit by hand. Run the script again after adding/removing images.')
  lines.push(' * Edit individual fields (title, location, etc.) directly in this file.')
  lines.push(' */')
  lines.push('')
  lines.push('export interface Photo {')
  lines.push('  src: string')
  lines.push('  title: string')
  lines.push('  date: string')
  lines.push('  camera?: string')
  lines.push('  lens?: string')
  lines.push('  aperture?: string')
  lines.push('  shutter?: string')
  lines.push('  iso?: string')
  lines.push('  focal?: string')
  lines.push('  location?: string')
  lines.push('}')
  lines.push('')
  lines.push('const photos: Photo[] = [')

  for (const p of photos) {
    const indent = '  '
    lines.push(`${indent}{`)
    lines.push(`${indent}  src: '${p.src}',`)
    lines.push(`${indent}  title: '${p.rawName}',`)
    lines.push(`${indent}  date: '${p.date}',`)
    if (p.camera) lines.push(`${indent}  camera: '${p.camera.replace(/'/g, "\\'")}',`)
    if (p.lens) lines.push(`${indent}  lens: '${p.lens.replace(/'/g, "\\'")}',`)
    if (p.aperture) lines.push(`${indent}  aperture: '${p.aperture}',`)
    if (p.shutter) lines.push(`${indent}  shutter: '${p.shutter}',`)
    if (p.iso) lines.push(`${indent}  iso: '${p.iso}',`)
    if (p.focal) lines.push(`${indent}  focal: '${p.focal}',`)
    if (p.location) lines.push(`${indent}  location: '${p.location.replace(/'/g, "\\'")}',`)
    lines.push(`${indent}},`)
  }

  lines.push(']')
  lines.push('')
  lines.push('export default photos')
  lines.push('')

  return lines.join('\n')
}

async function main() {
  // Warn if photos found in wrong directory (common mistake)
  const WRONG_DIR = join(ROOT, 'docs', 'gallery')
  try {
    const wrongEntries = await readdir(WRONG_DIR, { withFileTypes: true })
    const wrongImages = wrongEntries.filter(
      e => !e.isDirectory() && IMG_EXT.has(extname(e.name).toLowerCase()),
    )
    if (wrongImages.length > 0) {
      console.warn(`⚠️  Found ${wrongImages.length} image(s) in docs/gallery/ — wrong directory!`)
      console.warn('   Images must be in docs/.vuepress/public/gallery/')
      console.warn('   Move them and re-run:')
      for (const f of wrongImages)
        console.warn(`     mv docs/gallery/${f.name} docs/.vuepress/public/gallery/`)
      console.warn('')
    }
  } catch {}

  console.log('🔍 Scanning gallery directory...')
  const photos = await scanImages(GALLERY_DIR)
  console.log(`📸 Found ${photos.length} image(s)`)

  const content = generateDataFile(photos)
  await writeFile(DATA_FILE, content, 'utf-8')
  console.log(`✅ Wrote ${DATA_FILE}`)
}

main().catch((err) => {
  console.error('❌', err)
  process.exit(1)
})
